version: '3.8'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: compliance
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s


  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  postgres_data:
    name: compliance-postgres-data
    driver: local